red-hat-data-services/modelmesh-runtime-adapter

model-serving-puller/puller/puller.go
pullman/storageproviders/pvc/provider.go
pullman/storageproviders/pvc/provider_test.go

Merge from upstream 0.11.0-alpha

---

Dockerfile

[RHODS-12555] - CVE-2023-44487 - ubi8 bump

---

Dockerfile
go.mod

Update Go to 1.21

---

Dockerfile
go.mod

Update Go to 1.21, Fix h5py dependency error

---

.github/renovate.json

add renovate.json config

---

.github/renovate.json

Update renovate.json for tekton and dockerfile

---

.tekton/odh-modelmesh-runtime-adapter-v2-16-push.yaml

add tag and slack changes to tekton

---

Dockerfile.konflux

add Dockerfile.konflux for rhoai-2.8

---

.tekton/odh-modelmesh-runtime-adapter-v2-8-push.yaml

removing the python dependency

---

.tekton/odh-modelmesh-runtime-adapter-v2-8-push.yaml

Update odh-modelmesh-runtime-adapter to have only go

---

rpms.lock.yaml

update rpms.lock file

---

.github/renovate.json
Dockerfile
model-mesh-triton-adapter/scripts/tf_pb.py
rpms.lock.yaml

Sync ODH v2.26
[RHOAIENG-21097](https://issues.redhat.com/browse/RHOAIENG-21097)

Sync ODH v2.26 to RHOAI main

---

.tekton/odh-modelmesh-runtime-adapter-v2-20-push.yaml

[KONFLUX-2264,RHOAIENG-22432] add sast tasks to konflux

---

rpms.in.yaml
rpms.lock.yaml
ubi.repo

add ubi repo

---

Dockerfile.konflux

set unversioned python for alternatives

---

rpms.lock.yaml

updating rpm_lockfile

---

rpms.lock.yaml

Reverts red-hat-data-services/modelmesh-runtime-adapter#479

Revert "updating rpm_lockfile"

---

rpms.lock.yaml

[conforma] fix rpm repo IDs in rpms.lock.yaml

---

rpms.in.yaml
rpms.lock.yaml
ubi.repo

update rpms for 2.19

---

rpms.lock.yaml

- **update rpms for 2.19**
- **update rpms.lock.yaml**

update rpms 2.19

---

rpms.lock.yaml

update lock file

---

.tekton/odh-modelmesh-runtime-adapter-pull-request.yaml
rpms.in.yaml
rpms.lock.yaml

- update pr pipelines
- update rpms.(in|lock).yaml
JIRA: https://issues.redhat.com/browse/RHOAIENG-31754

(feat): Enable ARM build

---

.github/workflows/create-tag-release.yml
.tekton/odh-modelmesh-runtime-adapter-pull-request.yaml
.tekton/odh-modelmesh-runtime-adapter-push.yaml
.tekton/odh-modelmesh-runtime-adapter-v2-25-push.yaml
rpms.lock.yaml

Sync ODH stable-2.x branch into the RHODS rhoai-2.25 branch for the RHOAI 2.25 Code Freeze
[RHOAIENG-34403]

Sync/stable-2.x to rhoai-2.25 
